/* Generated By:JavaCC: Do not edit this line. langXConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface langXConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 14;
  /** RegularExpression Id. */
  int CLASS = 15;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int EXTENDS = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int NEW = 22;
  /** RegularExpression Id. */
  int PRINT = 23;
  /** RegularExpression Id. */
  int READ = 24;
  /** RegularExpression Id. */
  int RETURN = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int SUPER = 27;
  /** RegularExpression Id. */
  int CHAR = 28;
  /** RegularExpression Id. */
  int BOOLEAN = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int int_constant = 31;
  /** RegularExpression Id. */
  int string_constant = 32;
  /** RegularExpression Id. */
  int null_constant = 33;
  /** RegularExpression Id. */
  int intLiteral = 34;
  /** RegularExpression Id. */
  int floatliteral = 35;
  /** RegularExpression Id. */
  int stringliteral = 36;
  /** RegularExpression Id. */
  int IDENT = 37;
  /** RegularExpression Id. */
  int LETTER = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int LPAREN = 40;
  /** RegularExpression Id. */
  int RPAREN = 41;
  /** RegularExpression Id. */
  int LBRACE = 42;
  /** RegularExpression Id. */
  int RBRACE = 43;
  /** RegularExpression Id. */
  int LBRACKET = 44;
  /** RegularExpression Id. */
  int RBRACKET = 45;
  /** RegularExpression Id. */
  int SEMICOLON = 46;
  /** RegularExpression Id. */
  int COMMA = 47;
  /** RegularExpression Id. */
  int DOT = 48;
  /** RegularExpression Id. */
  int ASSIGN = 49;
  /** RegularExpression Id. */
  int GT = 50;
  /** RegularExpression Id. */
  int LT = 51;
  /** RegularExpression Id. */
  int EQ = 52;
  /** RegularExpression Id. */
  int LE = 53;
  /** RegularExpression Id. */
  int GE = 54;
  /** RegularExpression Id. */
  int NEQ = 55;
  /** RegularExpression Id. */
  int PLUS = 56;
  /** RegularExpression Id. */
  int MINUS = 57;
  /** RegularExpression Id. */
  int STAR = 58;
  /** RegularExpression Id. */
  int SLASH = 59;
  /** RegularExpression Id. */
  int REM = 60;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 61;
  /** RegularExpression Id. */
  int INVALID_CONST = 62;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int blockComment = 1;
  /** Lexical state. */
  int lineComment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "<token of kind 12>",
    "<token of kind 13>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"string\"",
    "\"super\"",
    "\"char\"",
    "\"boolean\"",
    "\"double\"",
    "<int_constant>",
    "<string_constant>",
    "\"null\"",
    "<intLiteral>",
    "<floatliteral>",
    "<stringliteral>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
